FROM golang:1.18 as build

WORKDIR /build
COPY . ./
RUN make build

FROM ubuntu:focal

WORKDIR /home
COPY --from=build /build/bin/cmd/ ./
RUN useradd -ms /bin/bash admin
RUN chown -R admin:admin /home 
RUN chmod 755 /home

RUN  mv ./cluster-manager ./wg-cni-cluster-manager 

RUN apt-get update && apt-get install -y \
    wireguard-tools jq iproute2 iptables \
 && rm -rf /var/lib/apt/lists/*

USER admin

EXPOSE 8080

ENTRYPOINT ["./wg-cni-cluster-manager"]

