apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wgcni-cluster-manager
  namespace: default
spec:
  selector:
    matchLabels:
      name: wgcni-cluster-manager
  template:
    metadata:
      labels:
        name: wgcni-cluster-manager
    spec:
      hostNetwork: true 
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - name: wgcni-cluster-manager
        image: shankeerthandocker/wg-cni-cluster-manager:v0.1
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        ports:
          - containerPort: 8080
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log